### ISSUE TITLE
Problem setting up on Mac

### ISSUE THREAD

**Issue by rogermc2** [ArturasAcus/GeometricAlgebra#1] opened 2020-04-01 01:57 UTC
Mac mini (2018)
OSX 10.14.6 Mojave
Mathematica 12.1.0.0
I seem to have problems with the installation of GA and will appreciate any help with getting GA going properly.
I followed the instructions in section 2.1 of GA.nb a number of times both from within GA.nb and by copying the commands into a separate notebook.
Results are in the attached file Setup.pdf
I'm not sure what is meant by "system file pointed by system variable". What is "system variable"?
I did ensure write permission for the folder containing `UnicodeCharacters.tr`.
After restarting Mathematica, I opened 01_Start.nb.
However, on executing the first command `"NotebookEvaluate[
 FileNameJoin[{ParentDirectory[
    NotebookDirectory[EvaluationNotebook[]]], "GA.nb"}]]"`, the response was:
~~~
(* Geometric algebra additions *)
0x26AC      \[GeometricProduct] ($gp$)      Infix       440 None    5   5
0x22CF      \[OuterProduct]     ($op$)      Infix       450 None    5   5
(* if instead of wedge you see vee symbol replace 0x22CE by 0x22CF *)
0x26ab      \[DorstProduct]     ($id$)      Infix       459 None    5   5
0x2219      \[InnerProduct]     ($ip$)      Infix       460 None    5   5
0x23A6      \[LeftContract]     ($il$)      Infix       461 None    5   5
0x23A3      \[RightContract]    ($ir$)      Infix       462 None    5   5
CopyFile::filex: Cannot overwrite existing file /Applications/Mathematica.app/Contents/SystemFiles/FrontEnd/TextResources/UnicodeCharacters.tr.old.
Syntax::sntufn: Unknown unicode longname GeometricProduct.
Syntax::sntufn: Unknown unicode longname RightContract.
Syntax::sntufn: Unknown unicode longname LeftContract.
Syntax::sntufn: Unknown unicode longname InnerProduct.
Syntax::sntufn: Unknown unicode longname DorstProduct.
~~~
plus numerous other syntax errors including those of the type:
~~~
Syntax::sntxf: "expr" cannot be followed by "\[GeometricProduct]prototype".
Syntax::sntxf: "(S+V1)" cannot be followed by "\[GeometricProduct]ps".
Syntax::sntxf: "expr" cannot be followed by "\[GeometricProduct]gaCliffordConjugate[expr]".
~~~

[Setup.pdf](https://github.com/ArturasAcus/GeometricAlgebra/files/4412287/Setup.pdf)

**Comment by ArturasAcus** [comment] 2020-04-01 06:21
Evaluate the  variable  System\`Dump\`unicodeCharactersTR in Mathematica notebook.

In[1] =System\`Dump\`unicodeCharactersTR
Out[1]="/home/acus/bin/Mathematica/12.0/SystemFiles/FrontEnd/TextResources/\
UnicodeCharacters.tr"

and it will return full path to the file your need to modify. In my
case it returned

"/home/acus/bin/Mathematica/12.0/SystemFiles/FrontEnd/TextResources/\
UnicodeCharacters.tr"

Simply speaking your need to append the content of provided
UnicodeCharactersAdd.tr to that file.

I don't typicaly use Mathematica commands for that. They were provided in order
to describe what to do in Mathematica language just to be consistent.

There are simple ways to accomplish the task. In any case first make a copy of original
UnicodeCharacters.tr file. In my case I would do (in terminal
application)

cp  /home/acus/bin/Mathematica/12.0/SystemFiles/FrontEnd/TextResources/\
UnicodeCharacters.tr 
  home/acus/bin/Mathematica/12.0/SystemFiles/FrontEnd/TextResources/\
UnicodeCharacters.tr.orig

Then either

1) Open  UnicodeCharacters.tr in text editor and copy the content of
the UnicodeCharactersAdd.tr to the very end of that file and save
changes.

or (in terminal application)

2) I better use command >> which appends the content of one file to the
other.  In my case

cat ./UnicodeCharactersAdd.tr >> 
/home/acus/bin/Mathematica/12.0/SystemFiles/FrontEnd/TextResources/\
UnicodeCharacters.tr

It was assumed that the command was issued in the folder where
UnicodeCharactersAdd.tr file is located.
Of course, if Mathematica is installed in a system wide location, your
will need administrator rights to make that change.


Thats it. This is the only modification which is needed.
Unfortunatelly, it changes the Mathematica system file and cannot be
easily automated by existing tools. The modification introduces nice
notations  for geometric products and sets it precedences.

Then after restarting Mathematica your should see nice symbols for the
all geometric product in a notebook Start.nb

**Comment by rogermc2** [comment] 2020-04-01 07:09
Thanks for the prompt reply.
However, after following your instructions I have a similar problem when, after quitting then restarting Mathematica, I open  `01_start.nb`  and, in accordance with the `01_start.nb` instruction
~~~
Load main notebook
Load package. WAIT until evaluation of cell is finished to be sure that no errors were produced.
~~~
 I execute 
~~~
NotebookEvaluate[
 FileNameJoin[{ParentDirectory[NotebookDirectory[EvaluationNotebook[]]], 
   "GA.nb"}]]
~~~
which results in:
~~~
(* Geometric algebra additions *)
0x26AC      \[GeometricProduct] ($gp$)      Infix       440 None    5   5
0x22CF      \[OuterProduct]     ($op$)      Infix       450 None    5   5
(* if instead of wedge you see vee symbol replace 0x22CE by 0x22CF *)
0x26ab      \[DorstProduct]     ($id$)      Infix       459 None    5   5
0x2219      \[InnerProduct]     ($ip$)      Infix       460 None    5   5
0x23A6      \[LeftContract]     ($il$)      Infix       461 None    5   5
0x23A3      \[RightContract]    ($ir$)      Infix       462 None    5   5

CopyFile::filex: Cannot overwrite existing file /Applications/Mathematica.app/Contents/SystemFiles/FrontEnd/TextResources/UnicodeCharacters.tr.old.

gaRunningAlgebra::shdw: Symbol gaRunningAlgebra appears in multiple contexts {GeometricAlgebra`,Global`}; definitions in context GeometricAlgebra` may shadow or be shadowed by other definitions.

Cl::shdw: Symbol Cl appears in multiple contexts {GeometricAlgebra`,Global`}; definitions in context GeometricAlgebra` may shadow or be shadowed by other definitions.

gaDefineInput::shdw: Symbol gaDefineInput appears in multiple contexts {GeometricAlgebra`,Global`}; definitions in context GeometricAlgebra` may shadow or be shadowed by other definitions.

gaDefineOrthonormalBasis::shdw: Symbol gaDefineOrthonormalBasis appears in multiple contexts {GeometricAlgebra`,Global`}; definitions in context GeometricAlgebra` may shadow or be shadowed by other definitions.

gaOrthonormalBasis::shdw: Symbol gaOrthonormalBasis appears in multiple contexts {GeometricAlgebra`,Global`}; definitions in context GeometricAlgebra` may shadow or be shadowed by other definitions.
~~~
plus numerous other errors including those of the type
~~~
Syntax::sntufn: Unknown unicode longname GeometricProduct.

Syntax::sntufn: Unknown unicode longname RightContract.

Syntax::sntufn: Unknown unicode longname LeftContract.
~~~
Attached is a text version of my `UnicodeCharacters.tr`.
(I deleted the comment lines in case they were causing the problem.)
[UnicodeCharacters.txt](https://github.com/ArturasAcus/GeometricAlgebra/files/4413256/UnicodeCharacters.txt)

**Comment by ArturasAcus** [comment] 2020-04-01 12:12
Probably You modified GA.nb when trying to install the package and then
forgot to make the installlation cells unevaluatable again. All cells
in the installiation section of the GA.nb should be unevaluatable(!)
after the corresponding modifications are made. From the output I see
that it tries to evaluate the cell from installation section (copying
the old file)
Anyway, I put the latest version (with many bug fixes) here
 
http://spektras.itpa.lt/~acus/GA/

Your UnicodeCharacters.txt looks good. So, take the new GA from the above link 
(also new example files from there). Then assuming that folder
structure  is unchanged (i.e. UsageExamples folder (which contains
Start.nb) is in the same folder as GA.nb notebook), your can open a
01_Start.nb and execute the first cell.

NotebookEvaluate[
 FileNameJoin[{ParentDirectory[
    NotebookDirectory[E
valuationNotebook[]]], "GA.nb"}]]


After it finishes (it loads all definitions) all other cells should
work as expected.
Note, that You do not have to evaluate GA.nb separately.

As an alternative your can also use the GA.nb without evaluating it from other notebook.

Simply open GA.nb and evaluate entire notebook (Mathematica menu command Evaluation/Evaluate Notebook).  It loads all definitions and here you will immediately will see errors, if any. Then close (or minimize the GA.nb) and open 01_Start.nb. In the 01_Start.nb
suppress evaluation of the cell, which calls GA.nb 

NotebookEvaluate[
 FileNameJoin[{ParentDirectory[
    NotebookDirectory[E
valuationNotebook[]]], "GA.nb"}]]

(In fact it should not do harm, and should issue warning that the package has already been loaded)
Then you can open any other notebook and use GA commands here.

Hope that helps. Let me know if something will go wrong.

**Comment by rogermc2** [comment] 2020-04-01 12:30
Thanks.
I've done further investigation and was in the midst of preparing some comments.
Essentially,  GA.nb didn't seem to be recognising the  UnicodeCharacters.tr additions.
Your latest advice will hopefully fix things.
I hadn't realized that I'd made the  installation cells evaluatable. That certainly explains at least part of my problem. Its not a feature of Mathematica that I'd previously known about.
Its getting a bit late at night for me here so I'll try your  latest version tomorrow morning.
Thanks again for the assistance.

**Comment by ArturasAcus** [comment] 2020-04-01 13:12
The additions to UnicodeCharacters.tr are not related to GA.nb. The addition should be recognized by Mathematica front end itself. I tested the additions with all versions of Mma starting from 8.0 to 12.0 and all were ok and working. On some Windows versions, however, default fonts didn't have representations of added new unicode symbols. That is why special style sheet was needed to change the Mathematica's default font. On Mac, however, as far as I remember (I tested only one version few years ago) all was ok. My suggestion is to check if indeed Mathematica loads the modified UnicodeCharacters.tr. The GA.nb simply replaces the added unicode character by proper command. 
For example, unicode character 0x26AC is replaced by GeometricProduct[] by GA.nb (with proper precedence). 

First in a fresh new Mathematica notebook evaluate

FilePrint[System\`Dump\`unicodeCharactersTR]

The symbol \` is a back quote (located near \<Esc> in my keyboard).

It will print the file with  the added characters in the end of the file. Check that once more and compare it with other lines. The syntax should be similar to some other lines.

Then in the Mathematica notebook press  press \<Esc>gp\<Esc>
It should produce nice small circle in the notebook. \<Esc> means pressing the corresponding keyboard character. gp stands for shortcut of first letters of  "geometric product". 

If that sequence did't produce any character that means there is a problem with UnicodeCharacters.tr  (may be something badly copied or new lines, or etc.) Then restore 
original UnicodeCharacters.tr and try to add them again again in other way. 

If the sequence is not producing a small circle and instead produces garbare or some wrong symbol (for example empty square, like in some Windows versions), then we have a problem with default Mathematica font (which is used for standard input) on Mac. The later issue can be resolved by choosing a font which has more complete character set. 

Note that a that point I even did't mention GA.nb file. Its all in the Mathematica system itself. 
By the way did your restarted Mathematica after UnicodeCharacters.tr modification? The front end should read these new settings on startup.

**Comment by rogermc2** [comment] 2020-04-02 00:08
Yes. Definitely not a problem with GA.nb.
I'll investigate changing the default font.

**Comment by rogermc2** [comment] 2020-04-02 06:35
I spent most of today solving the  additions to UnicodeCharacters.tr problems.
I finally discovered the apparent cause.
I was saving a copy of `UnicodeCharacters.tr` as `UnicodeCharacters copy.tr`.
Although I updated  `UnicodeCharacters.tr` correctly, Mathematica seemed to be using the `UnicodeCharacters copy.tr` file! Changing the name to `UnicodeCharacterscopy.tr` didn't help.
Mathematica only used my updated  `UnicodeCharacters.tr` when I named the backup copy  `UnicodeCharacters.tr.orig`.
Then the added symbols appeared in the files and `<Esc>gp<Esc>` worked correctly.
I probably would have been OK if I'd just relied on `UnicodeCharacters.tr.old` as my backup!
I then tried the first example program but other problems ensued during initialization.
I won't bother you with these at the moment but will tryout your  latest version.
Thanks for you assistance.

**Comment by rogermc2** [comment] 2020-04-02 06:54
I've downloaded your latest files.
However, I'm having the same problem as with the earlier version.
When I tried to run `GA.nb`, numerous `Syntax\[InvisbleSpace]` errors occur, the first of which occurs in the cell commencing with the instruction  `SetAttributes[{DeclareIntoContext}, {HoldAll, Listable}];' : 
![image](https://user-images.githubusercontent.com/12540410/78219171-b67d2900-750a-11ea-9aa8-eda4082710e0.png)

**Comment by ArturasAcus** [comment] 2020-04-02 07:10
Ok. Invisble space are special characters in Mathematica notebook. I do not see these characters in the listed cell. (You can mark the cell and press menu command Cell/Show Expression. This will show cell content. If you will see the \[InvisibleSpace] character that would mean that either file was modified during transfer or these were inserted by your Mathematica version. By the way, which version your use?

**Comment by ArturasAcus** [comment] 2020-04-02 07:42
Ok. I made tar.gz archive file and put it into http://spektras.itpa.lt/~acus/GA/.
Then unpack and try that. This will ensure that no damage occurs on download. If that will not help, then it is Mathematica importing issue (it inserts these spaces during import from previous version) and I probably could not help here.

**Comment by rogermc2** [comment] 2020-04-02 11:04
I'm using Mathematica 12.1.0.0.
I upgraded from version 11 to version 12 as when I first tried to open GA.nb Mathematica advised that  GA.nb  has been generated with a later version of Mathematica.
I am now working with the unpacked tar.gz archive file that you sent.
I divided the first problem cell to identify the problem expression which
turns out to be
~~~
Options[DeclareIntoContext] = {Context ->[Rule] $GAPackageContext};
~~~
I then retyped the line manually but the problem persists:
![image](https://user-images.githubusercontent.com/12540410/78240882-50ed6480-752b-11ea-8648-41f599242e43.png)
The expression is
~~~
Cell[BoxData[
 RowBox[{
  RowBox[{
   RowBox[{"Options", "[", "DeclareIntoContext", "]"}], "=", 
   RowBox[{"{", 
    RowBox[{"Context", 
     RowBox[{"->->[", "Rule", "]"}], "$GAPackageContext"}], "}"}]}], ";"}]], "Input",
 EmphasizeSyntaxErrors->True,
 CellLabel->"In[15]:="]
~~~
I'm wondering if the error label is misleading as the cell obviously does not contain a `\[InvisibleSpace]` symbol.
There is an option to turn off this message.
I doubt that is advisable?
The error message might be really suggesting that `Context\[Rule] $GAPackageContext` is invalid syntax?
Copy and pasting actually results in `Context ->[Rule] $GAPackageContext`.
That is, `\[Rule]` is reproduced as ` ->[Rule]`.

**Comment by ArturasAcus** [comment] 2020-04-02 11:54
"That is, \[Rule] is reproduced as ->[Rule]. " That is obviously wrong! It should be 
Context -> $GAPackageContext  or Context \[Rule] $GAPackageContext  . Seems like it the nice symbol of Rule (which is represented as \\[Rule] ) causes problems. In any way in my notebook GA.nb which I packed there is only a single Rule!.  In particular the relevant part  in my notebook is 
RowBox[{"Context", " ", "\\[Rule]", " ", "$GAPackageContext"}]

It seems that rule is "doubled"   since instead ->[Rule] should be just -> 

When a notebook is so badly corrupted I doubt if your can properly work with it, since most probably there are many similar places. May be your can try to open it on some other computer or in other Mathematica version? It is simply hard to believe that the notebook import between different systems can be so buggy. I started to write the package in version 7. And that part your show is the most old. I had never any problems neither using the same notebook produced with older version with newer Mma versions nor in a reverse way, i.e opening the notebook produced with newer Mathematica version in the old version was fine also!

**Comment by rogermc2** [comment] 2020-04-02 23:16
OK.
Thanks very much for your comments.
I also find it quite unbelievable that so much corruption is occurring.
Others notebooks of mine have all error messages mislabelled as `\[InvisibleSpace]` errors.
I've just reinstalled Mathematica 11 and have run GA.nb successfully with it but haven't  updated UnicodeCharacters.tr yet.

**Comment by rogermc2** [comment] 2020-04-03 00:01
Reinstalled Mathematica 12 and have run GA.nb successfully with it before modifying UnicodeCharacters.tr.
Modifing `UnicodeCharacters.tr` using Mathematica causes the `\[InvisibleSpace]` problem.
on restoring `UnicodeCharacters.tr` from `UnicodeCharacters.tr.old` GA.nb again runs successfully.
Next, I saved the 'UnicodeCharactersAdd.tr' changes as a text file then updated  `UnicodeCharacters.tr` from the text file using TextEdit.
Restarted Mathematica 12.
GA.nb executed with out errors.
01_Start.nb `NotebookEvaluate[
 FileNameJoin[{ParentDirectory[
    NotebookDirectory[EvaluationNotebook[]]], "GA.nb"}]]` now evaluates without errors.
Problem finally solved.
Many thanks for your assistance.

**Closed as completed** 2020-04-03 00:28 UTC
